import {LineEdit, Button, VerticalBox, HorizontalBox, CheckBox, TabWidget, AboutSlint, ComboBox, Switch, Spinner}from "std-widgets.slint";

component TitleBar inherits Rectangle {
    border-color: black;
    border-width: 2px;

    HorizontalLayout {
        Rectangle {
            border-color: black;
            border-width: 2px;
            background: white;
            height: parent.height;
            width: parent.height;
            Image {
                source: @image-url("../res/CTR_logo.png");
                height: parent.height - 4 * 1px;
                width: parent.height - 4 * 1px;
            }
        }

        Text {
            text: "CTR Randomizer (pre-alpha)";
            font-weight: 800;
            font-size: 40pt;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}

//component SettingsMetaBar inherits Rectangle {
//    HorizontalLayout {
//        alignment: space-evenly;
//        padding: 4px;
//        Text {
//            text: "Settings Hash:";
//            vertical-alignment: center;
//            horizontal-alignment: center;
//            font-size: 20pt;
//        }
//
//        VerticalBox {
//            alignment: space-evenly;
//            LineEdit {
//                height: parent.height / 2;
//                width: 200px;
//                horizontal-alignment: left;
//                read-only: true;
//            }
//        }
//
//        Button {
//            text: "Export Settings";
//            height: parent.height * (2/3);
//            width: 200px;
//        }
//        Button {
//            text: "Import Settings";
//            height: parent.height * (2/3);
//            width: 200px;
//        }
//    }
//}

component RandomizationSubmenu inherits Rectangle {
    out property <int> shuffle_adventure <=> chosen_randomization.current-index;
    out property <bool> shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems;
    out property <bool> shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> warppad_unlocks.current-index;
    out property <bool> autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> bossgarage_unlocks.current-index;

    VerticalLayout {
        Rectangle {
            height: 60px;
            border-color: black;
            border-width: 1px;
            Text {
                x: 380px;
                y: 22px;
                text: "Randomize:";
                font-size: 10pt;
                font-weight: 800;
            }
            chosen_randomization := ComboBox {
                x: 480px;
                y: 14px;
                width: 200px;
                model: ["Nothing", "Adventure"];
                current-index: 1;
            }
        }
        Rectangle {
            visible: chosen_randomization.current-index == 1;
            Text {
                y: 14px;
                text: "Adventure Randomization";
                font-size: 12pt;
                font-weight: 800;
            }

            Rectangle {
                width: root.width * 0.65;
                height: 40px;
                y: 30px;
                border-width: shuffle_reward.x == (self.width/2)-300px ? 1px : 0px;
                border-color: black;
                border-radius: 10px;
                shuffle_reward := Switch {
                    x: self.checked ? (parent.width/2)-300px : (parent.width/2)-96px;
                    animate x {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                    text: "Shuffle Race Rewards";
                    toggled => {root.shuffle_race_rewards = self.checked}
                }
                Switch {
                    text: "Include Keys";
                    visible: shuffle_reward.x == (parent.width/2)-300px;
                    toggled => {root.shuffle_race_rewards_keys = self.checked}
                }
                Switch {
                    x: (parent.width/2)+130px;
                    text: "Include Gems";
                    visible: shuffle_reward.x == (parent.width/2)-300px;
                    toggled => {root.shuffle_race_rewards_gems = self.checked}
                }
            }
            Rectangle {
                width: root.width * 0.65;
                height: 40px;
                y: 70px;
                border-width: shuffle_warppads.x == (self.width/2)-300px ? 1px : 0px;
                border-color: black;
                border-radius: 10px;
                shuffle_warppads := Switch {
                    x: self.checked ? (parent.width/2)-300px : (parent.width/2)-84px;
                    animate x {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                    text: "Shuffle Warp Pads";
                    toggled => {root.shuffle_warppads = self.checked}
                }
                Switch {
                    text: "Include Battle Arenas";
                    visible: shuffle_warppads.x == (parent.width/2)-300px;
                    toggled => {root.shuffle_warppads_battlearenas = self.checked}
                }
                Switch {
                    x: (parent.width/2)+130px;
                    text: "Include Gem Cups";
                    visible: shuffle_warppads.x == (parent.width/2)-300px;
                    toggled => {root.shuffle_warppads_gemcups = self.checked}
                }
            }
            Text {
                y: 130px;
                x: parent.x + 310px;
                text: "Warp Pad Unlock Requirements";
                font-size: 10pt;
            }
            warppad_unlocks := ComboBox {
                y: 122px;
                x: 530px;
                model: ["Vanilla", "Shuffled", "More Choices", "Wild", "Chaotic"];
            }
            Text {
                y: 170px;
                x: parent.x + 379px;
                text: "Boss Garage Unlocks";
                font-size: 10pt;
            }
            bossgarage_unlocks := ComboBox {
                y: 162px;
                x: 530px;
                model: ["Original 4 Tracks", "Same Hub Tracks", "4 / 8 / 12 / 16 Trophies"];
            }
            Switch {
                y: 210px;
                text: "Auto-Unlock CTR Challenge & Relic Race";
                toggled => {root.autounlock_ctrchallenge_relicrace = self.checked}
            }
        }
    }
}

component GeneralSubmenu inherits Rectangle {
    out property <int> rr_required_minimum_time <=> required_minimum_time.current-index;
    out property <bool> rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> oxide_final_unlock.current-index;

    VerticalLayout {
        alignment: start;
        width: 500px;
        HorizontalBox {
            height: 60px;
            Text {
                vertical-alignment: center;
                text: "Relic Races: Required Minimum Time";
            }
            required_minimum_time := ComboBox {
                width: 250px;
                model: ["Any Time", "Gold Time or better", "Platinum Time"];
            }
        }
        Switch {
            x: 6px;
            text: "Relic Races: Require Perfects";
            toggled => {root.rr_require_perfects = self.checked}
        }
        HorizontalBox {
            height: 60px;
            Text {
                vertical-alignment: center;
                text: "Oxide's Final Challenge Unlock";
            }
            oxide_final_unlock := ComboBox {
                width: 250px;
                model: ["18 Sapphire Relics", "18 Gold+Platinum Relics"];
            }
        }
    }
}

component QoLSubmenu inherits Rectangle {
    out property <bool> qol_skip_mask_hints;
    out property <bool> qol_skip_podium;
    out property <bool> qol_skip_mask_congrats;

    Switch {
        y: 10px;
        height: 50px;
        text: "Skip Mask Hints";
        toggled => {root.qol_skip_mask_hints = self.checked}
    }
    Switch {
        y: 60px;
        height: 50px;
        text: "Auto-Skip Podium Cutscenes";
        toggled => {root.qol_skip_podium = self.checked}
    }
    Switch {
        y: 110px;
        height: 50px;
        text: "Skip Mask Congrats";
        toggled => {root.qol_skip_mask_congrats = self.checked}
    }
}

component AboutSubmenu inherits Rectangle {
    callback sources_generator();
    callback sources_mod();

    Text {
        y: 10px;
        text: "The CTR Randomizer mod is made by";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    Text {
        y: 30px;
        text: "wiz_taor";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    Text {
        y: 50px;
        text: "Icebound777";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }

    Text {
        y: 100px;
        text: "Sources of this seed generator:";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    TouchArea {
        height: 30px;
        width: 75px;
        y: 120px;
        clicked => {root.sources_generator();}
        Button {
            enabled: false;
            height: 34px;
            width: 80px;
        }
        Image {
            source: @image-url("../res/GitHub_Logo.png");
            height: 30px;
            width: 75px;
        }
    }

    Text {
        y: 160px;
        text: "Sources of the randomizer mod:";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    TouchArea {
        height: 30px;
        width: 75px;
        y: 180px;
        clicked => {root.sources_mod();}
        Button {
            enabled: false;
            height: 34px;
            width: 80px;
        }
        Image {
            source: @image-url("../res/GitHub_Logo.png");
            height: 30px;
            width: 75px;
        }
    }

    AboutSlint {
        x: 370px;
        y: 170px;
        height: 150px;
    }
    Text {
        y: 300px;
        text: "('User Interface design is my passion' lmao)";
        horizontal-alignment: center;
        vertical-alignment: top;
        font-weight: 800;
        font-size: 8pt;
    }
}

component SettingsMenu inherits TabWidget {
    callback sources_generator();
    callback sources_mod();

    out property <int> shuffle_adventure <=> randomization.shuffle_adventure;
    out property <bool> shuffle_race_rewards <=> randomization.shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys <=> randomization.shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems <=> randomization.shuffle_race_rewards_gems;
    out property <bool> shuffle_warppads <=> randomization.shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas <=> randomization.shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups <=> randomization.shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> randomization.warppad_unlock_requirements;
    out property <bool> autounlock_ctrchallenge_relicrace <=> randomization.autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> randomization.bossgarage_unlock_requirements;

    out property <int> rr_required_minimum_time <=> generalmenu.rr_required_minimum_time;
    out property <bool> rr_require_perfects <=> generalmenu.rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> generalmenu.rr_required_minimum_time;

    out property <bool> qol_skip_mask_hints <=> qolmenu.qol_skip_mask_hints;
    out property <bool> qol_skip_podium <=> qolmenu.qol_skip_podium;
    out property <bool> qol_skip_mask_congrats <=> qolmenu.qol_skip_mask_congrats;

    current-index: 0;
    Tab {
        title: "Randomization";
        randomization := RandomizationSubmenu {}
    }
    Tab {
        title: "General";
        generalmenu := GeneralSubmenu {}
    }
    Tab {
        title: "Quality of Life";
        qolmenu := QoLSubmenu {}
    }
    Tab {
        title: "About";
        AboutSubmenu {
            sources_generator() => { root.sources_generator(); }
            sources_mod() => { root.sources_mod(); }
        }
    }
}

component RomOutputBar inherits Rectangle {
    callback gen_seed();
    callback pick_rom();
    in-out property <string> rom_path;
    in property <bool> can_generate;
    in property <int> rom_valid_state;

    out property <bool> write_spoilerlog: true;

    HorizontalLayout {
        Rectangle {
            width: parent.width / 2;
            border-color: black;
            border-width: 1px;

            Text {
                x: 16px;
                text: "ROM:";
                font-weight: 800;
                vertical-alignment: center;
            }
            TouchArea {
                x: 60px;
                width: 350px;
                height: parent.height / 2;
                clicked => {root.pick_rom()}
                LineEdit {
                    width: 350px;
                    placeholder-text: rom_path.is-empty ? "Click here to choose CTR NTSC-U ROM ..." : rom_path;
                    enabled: false;
                }
            }
            Text {
                visible: root.rom_valid_state == 2 || root.rom_valid_state == 3;
                x: 430px;
                text: root.rom_valid_state == 3 ? "Valid": "Invalid";
                font-weight: 800;
                color: root.rom_valid_state == 3 ? green : red;
                vertical-alignment: center;
            }
            Text {
                visible: rom_valid_state == 1;
                x: 430px;
                text: "Validating ROM ...";
                font-weight: 800;
                color: red;
                vertical-alignment: center;
            }
        }
        Rectangle {
            border-color: black;
            border-width: 1px;

                Switch {
                    x: 30px;
                    text: "Generate Spoilerlog";
                    checked: true;
                    toggled => { root.write_spoilerlog = self.checked }
                }

                Button {
                    x: 250px;
                    width: 200px;
                    text: "Generate Seed";
                    height: parent.height * (2/3);
                    enabled: can_generate;
                    clicked => {root.gen_seed()}
                }

                Spinner {
                    x: 460px;
                    progress: 0.9;
                }
        }
    }
}

export component MainWindow inherits Window {
    title: "CTR Randomizer";
    width: 1000px;
    height: 600px;
    callback gen_seed();
    callback pick_rom();
    callback sources_generator();
    callback sources_mod();
    in-out property <string> rom_path;
    in property <bool> can_generate: false;
    in property <int> rom_valid_state: 0;

    out property <bool> write_spoilerlog <=> romoutput.write_spoilerlog;

    out property <int> shuffle_adventure <=> settings.shuffle_adventure;
    out property <bool> shuffle_race_rewards <=> settings.shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys <=> settings.shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems <=> settings.shuffle_race_rewards_gems;
    out property <bool> shuffle_warppads <=> settings.shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas <=> settings.shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups <=> settings.shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> settings.warppad_unlock_requirements;
    out property <bool> autounlock_ctrchallenge_relicrace <=> settings.autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> settings.bossgarage_unlock_requirements;

    out property <int> rr_required_minimum_time <=> settings.rr_required_minimum_time;
    out property <bool> rr_require_perfects <=> settings.rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> settings.rr_required_minimum_time;

    out property <bool> qol_skip_mask_hints <=> settings.qol_skip_mask_hints;
    out property <bool> qol_skip_podium <=> settings.qol_skip_podium;
    out property <bool> qol_skip_mask_congrats <=> settings.qol_skip_mask_congrats;

    VerticalLayout {
        TitleBar {
            height: parent.height * 0.18;
        }
        //SettingsMetaBar {
        //    height: parent.height * 0.1;
        //}
        settings := SettingsMenu {
            sources_generator() => { root.sources_generator(); }
            sources_mod() => { root.sources_mod(); }
        }
        romoutput := RomOutputBar {
            height: parent.height * 0.13;
            rom_path: root.rom_path;
            can_generate: root.can_generate;
            rom_valid_state: root.rom_valid_state;

            gen_seed() => { root.gen_seed(); }
            pick_rom() => { root.pick_rom(); }
        }
    }
}
