import {LineEdit, Button, VerticalBox, HorizontalBox, CheckBox, TabWidget, AboutSlint, ComboBox, Switch, Spinner, Palette}from "std-widgets.slint";

export component ToolTip inherits Window {
    // Blatently yoink'd from github issues discussion on missing tooltip
    // functionality on the slint repo
    in property <string> text  <=> text.text;
    in property <bool> user_is_hovering;

    property <bool> has_waited;
    z: 100;

    visible: has_waited && user_is_hovering;
    Rectangle {
        visible: parent.visible;
        background: Palette.background;
        border-radius: 0.5rem;
        border-color: black;
        border-width: 1px;
        drop-shadow-color: gray;
        drop-shadow-blur: 3px;
        drop-shadow-offset-x: 5px;
        drop-shadow-offset-y: 5px;

        text := Text {
            width: parent.width - 1rem;
            height: parent.height - 1rem;
            font-size: root.default-font-size * 0.9;
            horizontal-alignment: left;
            vertical-alignment: top;
            wrap: word-wrap;
        }
    }

    Timer {
        // Delay until tooltip appears.
        interval: 0.5s;
        running: parent.user_is_hovering || self.needs_resetting;
        // The resetting property allows the timer to reset to the default state
        // where it has not waited to show the tooltip yet. This is needed
        // because we can not listen to a "not hovering anymore" event. Thus, we
        // let the timer run a little bit longer and reset the state before
        // stopping `running`.
        property <bool> needs_resetting : false;
        triggered() => {
            if needs_resetting && !parent.user_is_hovering {
                // User is not hovering anymore.
                parent.has_waited = false;
                needs_resetting = false;
            } else {
                // User is hovering and waited, so tooltip can be shown.
                parent.has_waited = true;
                needs_resetting = true;
            }
        }
    }
}

component TitleBar inherits Rectangle {
    border-color: black;
    border-width: 2px;

    HorizontalLayout {
        Rectangle {
            border-color: black;
            border-width: 2px;
            background: white;
            height: parent.height;
            width: parent.height;
            Image {
                source: @image-url("../res/CTR_logo.png");
                height: parent.height - 4 * 1px;
                width: parent.height - 4 * 1px;
            }
        }

        Text {
            text: "CTR-Randomizer (alpha 1)";
            font-weight: 800;
            font-size: 40pt;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}

//component SettingsMetaBar inherits Rectangle {
//    HorizontalLayout {
//        alignment: space-evenly;
//        padding: 4px;
//        Text {
//            text: "Settings Hash:";
//            vertical-alignment: center;
//            horizontal-alignment: center;
//            font-size: 20pt;
//        }
//
//        VerticalBox {
//            alignment: space-evenly;
//            LineEdit {
//                height: parent.height / 2;
//                width: 200px;
//                horizontal-alignment: left;
//                read-only: true;
//            }
//        }
//
//        Button {
//            text: "Export Settings";
//            height: parent.height * (2/3);
//            width: 200px;
//        }
//        Button {
//            text: "Import Settings";
//            height: parent.height * (2/3);
//            width: 200px;
//        }
//    }
//}

component RandomizationSubmenu inherits Rectangle {
    out property <int> shuffle_adventure <=> chosen_randomization.current-index;
    out property <bool> shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems;
    out property <bool> shuffle_race_rewards_plat_relics;
    out property <bool> shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> warppad_unlocks.current-index;
    out property <bool> autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> bossgarage_unlocks.current-index;

    VerticalLayout {
        Rectangle {
            height: 60px;
            border-color: black;
            border-width: 1px;
            Text {
                x: 380px;
                y: 22px;
                text: "Randomize:";
                font-size: 10pt;
                font-weight: 800;
            }
            chosen_randomization := ComboBox {
                x: 480px;
                y: 14px;
                width: 200px;
                model: ["Nothing", "Adventure"];
                current-index: 1;
            }
        }
        Rectangle {
            visible: chosen_randomization.current-index == 1;
            Text {
                y: 14px;
                text: "Adventure Randomization";
                font-size: 12pt;
                font-weight: 800;
            }

            shuffle_reward_box := Rectangle {
                width: root.width * 0.55;
                height: shuffle_reward.checked ? 80px : 40px;
                animate height {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                y: 40px;
                border-width: self.height == 80px ? 1px : 0px;
                border-color: black;
                border-radius: 10px;
                shuffle_reward_touch := TouchArea {
                    y: 0px;
                    width: 200px;
                    height: 38px;
                    shuffle_reward := Switch {
                        x: (parent.width/2)-96px;
                        y: 10px;
                        //animate x {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                        text: "Shuffle Race Rewards";
                        toggled => {
                            root.shuffle_race_rewards = self.checked;
                            if (!self.checked && bossgarage_unlocks.current-index == 0) {
                                bossgarage_unlocks.current-index = 1;
                            }
                        }
                    }
                }
                include_keys_touch := TouchArea {
                    x: (shuffle_reward_box.width/2) - 250px;
                    y: 45px;
                    width: 140px;
                    height: 28px;
                    enabled: shuffle_reward_box.height == 80px;
                    Switch {
                        text: "Include Keys";
                        x: 0px;
                        y: 0px;
                        visible: shuffle_reward_box.height == 80px;
                        toggled => {root.shuffle_race_rewards_keys = self.checked}
                    }
                }
                include_gems_touch := TouchArea {
                    x: (shuffle_reward_box.width/2) - 100px;
                    y: 45px;
                    width: 140px;
                    height: 28px;
                    enabled: shuffle_reward_box.height == 80px;
                    Switch {
                        x: 0px;
                        y: 0px;
                        text: "Include Gems";
                        visible: shuffle_reward_box.height == 80px;
                        toggled => {root.shuffle_race_rewards_gems = self.checked}
                    }
                }
                include_plats_touch := TouchArea {
                    x: (shuffle_reward_box.width/2) + 50px;
                    y: 45px;
                    width: 210px;
                    height: 28px;
                    enabled: shuffle_reward_box.height == 80px;
                    Switch {
                        x: 0px;
                        y: 0px;
                        text: "Include Platinum Relics";
                        visible: shuffle_reward_box.height == 80px;
                        toggled => {root.shuffle_race_rewards_plat_relics = self.checked}
                    }
                }
            }
            warppads_box := Rectangle {
                width: root.width * 0.65;
                height: 40px;
                y: shuffle_reward.checked ? 120px : 80px;
                animate y {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                border-width: shuffle_warppads_touch.x == (self.width/2)-310px ? 1px : 0px;
                border-color: black;
                border-radius: 10px;
                shuffle_warppads_touch := TouchArea {
                    width: 190px;
                    height: 28px;
                    x: shuffle_warppads.checked ? (parent.width/2)-310px : (parent.width/2)-94px;
                    animate x {duration: 300ms; delay: 100ms; easing: ease-in-out-quad;}
                    shuffle_warppads := Switch {
                        text: "Shuffle Warp Pads";
                        toggled => {root.shuffle_warppads = self.checked}
                    }
                }
                include_battlearenas_touch := TouchArea {
                    width: 190px;
                    height: 28px;
                    enabled: shuffle_warppads_touch.x == (warppads_box.width/2)-310px;
                    Switch {
                        text: "Include Battle Arenas";
                        visible: shuffle_warppads_touch.x == (warppads_box.width/2)-310px;
                        toggled => {root.shuffle_warppads_battlearenas = self.checked}
                    }
                }
                include_gemcups_touch := TouchArea {
                    width: 190px;
                    height: 28px;
                    x: (warppads_box.width/2)+130px;
                    enabled: shuffle_warppads_touch.x == (warppads_box.width/2)-310px;
                    Switch {
                        x: 0px;
                        text: "Include Gem Cups";
                        visible: shuffle_warppads_touch.x == (warppads_box.width/2)-310px;
                        toggled => {root.shuffle_warppads_gemcups = self.checked}
                    }
                }
            }
            warppad_unlocks_touch := TouchArea {
                width: 420px;
                height: 34px;
                y: warppads_box.y + 41px;
                warppad_unlocks_text := Text {
                    x: warppad_unlocks.x + 200px;
                    text: "Warp Pad Unlock Requirements";
                    font-size: 10pt;
                }
                warppad_unlocks := ComboBox {
                    enabled: false;
                    y: warppad_unlocks_text.y - 8px;
                    x: 10px;
                    width: 190px;
                    model: ["Vanilla", "Shuffled", "Chaotic"];
                }
            }
            bossgarage_unlocks_touch := TouchArea {
                width: 420px;
                height: 34px;
                y: warppad_unlocks_touch.y + 38px;
                bossgarage_unlocks_text := Text {
                    x: bossgarage_unlocks.x + 200px;
                    text: "Boss Garage Unlocks";
                    font-size: 10pt;
                }
                bossgarage_unlocks := ComboBox {
                    y: bossgarage_unlocks_text.y - 8px;
                    x: 10px;
                    current-index: 1;
                    width: 190px;
                    model: ["Original 4 Tracks", "Same Hub Tracks", "4 / 8 / 12 / 16 Trophies"];
                    selected(current-value) => {
                        if (!shuffle_reward.checked && self.current-index == 0) {
                            self.current-index = 1;
                        }
                    }
                }
            }
            auto_unlock_stagetwo_touch := TouchArea {
                width: 340px;
                height: 34px;
                y: bossgarage_unlocks_touch.y + 42px;
                Switch {
                    enabled: false;
                    text: "Auto-Unlock CTR Challenge & Relic Race";
                    toggled => {root.autounlock_ctrchallenge_relicrace = self.checked}
                }
            }
        }
    }

    ToolTip {
        x: shuffle_reward_touch.x + 340px;
        y: shuffle_reward_touch.y + 140px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "OFF: All race rewards will be unchanged.\n\n"
        + "ON: All Trophies, CTR Tokens, Sapphire Relics, and Gold Relics will "
        + "be shuffled. Also opens up more race reward options.";
        user_is_hovering: shuffle_reward_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: include_keys_touch.x + 320px;
        y: include_keys_touch.y + 130px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "OFF: Keys are always rewards for beating bosses.\n\n"
        + "ON: Keys will be shuffled together with the other rewards.";
        user_is_hovering: include_keys_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: include_gems_touch.x + 320px;
        y: include_gems_touch.y + 130px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "OFF: Gems are always rewards for winning gem cups.\n\n"
        + "ON: Gems will be shuffled together with the other rewards.";
        user_is_hovering: include_gems_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: include_plats_touch.x + 320px;
        y: include_plats_touch.y + 130px; // <-- references any or no component, not necessarily a TouchArea
        height: 9rem;
        width: 25rem;
        text: "OFF: Platinum Relics are always rewards for beating platinum times.\n"
        + "Additionally, beating platinum times will never be required to beat the game.\n\n"
        + "ON: Platinum Relics will be shuffled together with the other rewards.";
        user_is_hovering: include_plats_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: shuffle_warppads_touch.x + 300px;
        y: shuffle_warppads_touch.y + 170px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "OFF: All warp pads lead to their original levels.\n\n"
        + "ON: All trophy-race and relic-race warp pads will be shuffled. "
        + "Also opens up more warp pad options.";
        user_is_hovering: shuffle_warppads_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: include_battlearenas_touch.x + 300px;
        y: include_battlearenas_touch.y + 170px; // <-- references any or no component, not necessarily a TouchArea
        height: 14rem;
        width: 25rem;
        text: "OFF: The four battle arena warp pads (Crystal Challenges) lead "
        + "to their original levels.\n\n"
        + "ON: The battle arena warp pads will be shuffled with the other warp "
        + "pads.\n\n"
        + "Note: If 'Warp Pad Unlock Requirements' are set to 'Vanilla' and "
        + "'Shuffle Race Rewards' is turned off, then these warp pads can only "
        + "shuffle among themselves (or with gem cup pads, if those are "
        + "shuffled as well).";
        user_is_hovering: include_battlearenas_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: include_gemcups_touch.x + 240px;
        y: include_gemcups_touch.y + 170px; // <-- references any or no component, not necessarily a TouchArea
        height: 14rem;
        width: 25rem;
        text: "OFF: The five gem cup warp pads lead to their original levels.\n\n"
        + "ON: The gem cup warp pads will be shuffled with the other warp "
        + "pads.\n\n"
        + "Note: If 'Warp Pad Unlock Requirements' are set to 'Vanilla' and "
        + "'Shuffle Race Rewards' is turned off, then these warp pads can only "
        + "shuffle among themselves (or with battle arena pads, if those are "
        + "shuffled as well).";
        user_is_hovering: include_gemcups_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: warppad_unlocks_touch.x + 240px;
        y: warppad_unlocks_touch.y + 100px; // <-- references any or no component, not necessarily a TouchArea
        height: 2rem;
        width: 16rem;
        text: "NYI: NOT YET IMPLEMENTED";
        user_is_hovering: warppad_unlocks_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: bossgarage_unlocks_touch.x + 240px;
        y: bossgarage_unlocks_touch.y + 100px; // <-- references any or no component, not necessarily a TouchArea
        height: 10rem;
        width: 25rem;
        text: "Choose how the regular boss garages get unlocked.\n"
        + "'Original 4 Tracks' and 'Same Hub Tracks' behave the same if the "
        + "warp pads are not shuffled.\n\n"
        + "Note: 'Original 4 Tracks' requires rewards to be shuffled.";
        user_is_hovering: bossgarage_unlocks_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: auto_unlock_stagetwo_touch.x + 220px;
        y: auto_unlock_stagetwo_touch.y + 90px; // <-- references any or no component, not necessarily a TouchArea
        height: 2rem;
        width: 16rem;
        text: "NYI: NOT YET IMPLEMENTED";
        user_is_hovering: auto_unlock_stagetwo_touch.has-hover; // <-- references one or more TouchArea below
    }
}

component GeneralSubmenu inherits Rectangle {
    out property <int> rr_required_minimum_time <=> required_minimum_time.current-index;
    out property <bool> rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> oxide_final_unlock.current-index;

    VerticalLayout {
        alignment: start;
        width: 500px;
        padding-top: 10px;
        requireperfects_touch := TouchArea {
            width: 250px;
            height: 50px;
            x: 10px;
            Switch {
                width: parent.width;
                height: parent.height;
                text: "Relic Races: Require Perfects";
                toggled => {root.rr_require_perfects = self.checked}
            }
        }

        minimumtime_touch := TouchArea {
            HorizontalBox {
                height: 50px;
                required_minimum_time := ComboBox {
                    width: 210px;
                    model: ["Any Time", "Gold Time or better", "Platinum Time"];
                }
                Text {
                    vertical-alignment: center;
                    text: "Relic Races: Required Minimum Time";
                }
            }
        }
        finalchallenge_touch := TouchArea {
            HorizontalBox {
                height: 50px;
                oxide_final_unlock := ComboBox {
                    width: 210px;
                    model: ["18 Sapphire Relics", "18 Gold+Platinum Relics"];
                }
                Text {
                    vertical-alignment: center;
                    text: "Oxide's Final Challenge Unlock";
                }
            }
        }
    }

    ToolTip {
        x: requireperfects_touch.x + 300px;
        y: requireperfects_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 9rem;
        width: 25rem;
        text: "OFF: Reaching the required relic time suffices to get one or more prizes.\n\n"
        + "ON: To get one or more prizes from a relic race, not only do the relic times need "
        + "to be bested, but all time boxes have to be broken during that run as well.";
        user_is_hovering: requireperfects_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: minimumtime_touch.x + 400px;
        y: minimumtime_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "Choose the required minimum relic time to beat to get any prizes.\n"
        + "If you choose Gold or Platinum as minimum time, then upon reaching that "
        + "time the lower rank prize(s) will also be awarded.";
        user_is_hovering: minimumtime_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: finalchallenge_touch.x + 400px;
        y: finalchallenge_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 12rem;
        width: 25rem;
        text: "Choose what types of relics are required to turn Oxide's Challenge into "
        + "Oxide's Final Challenge.\n\n"
        + "18 Sapphire Relics: You need all 18 Sapphire relics (Golds and Platinums are ignored).\n\n"
        + "18 Gold+Platinum Relics: You need at least a combined total of 18 Gold relics and Platinum relics.";
        user_is_hovering: finalchallenge_touch.has-hover; // <-- references one or more TouchArea below
    }
}

component QoLSubmenu inherits Rectangle {
    out property <bool> qol_skip_mask_hints;
    out property <bool> qol_skip_podium;
    out property <bool> qol_skip_mask_congrats;
    out property <bool> trick_helper_tiziano;
    out property <bool> trick_helper_ta;

    HorizontalLayout {
        VerticalLayout {
            width: parent.width/2;
            padding-top: 20px;

            Text {
                text: "Quality of Life";
                height: 20px;
                font-size: 12pt;
                font-weight: 800;
                horizontal-alignment: center;
            }

            skipmaskhint_touch := TouchArea {
                width: 160px;
                height: 50px;
                x: 135px;
                Switch {
                    width: parent.width;
                    height: parent.height;
                    text: "Skip Mask Hints";
                    toggled => {root.qol_skip_mask_hints = self.checked}
                }
            }
            skippodium_touch := TouchArea {
                width: 250px;
                height: 50px;
                x: 135px;
                Switch {
                    width: parent.width;
                    height: parent.height;
                    text: "Auto-Skip Podium Cutscenes";
                    toggled => {root.qol_skip_podium = self.checked}
                }
            }
            skipmaskcongrats_touch := TouchArea {
                width: 190px;
                height: 50px;
                x: 135px;
                Switch {
                    width: parent.width;
                    height: parent.height;
                    text: "Skip Mask Congrats";
                    toggled => {root.qol_skip_mask_congrats = self.checked}
                }
            }
        }
        VerticalLayout {
            width: parent.width/2;
            padding-top: 20px;

            Text {
                text: "Tricks";
                height: 20px;
                font-size: 12pt;
                font-weight: 800;
                horizontal-alignment: center;
            }
            helper_tiziano_touch := TouchArea {
                width: 160px;
                height: 50px;
                x: 172px;
                Switch {
                    width: parent.width;
                    height: parent.height;
                    text: "Tiziano Helper";
                    toggled => {root.trick_helper_tiziano = self.checked}
                }
            }
            helper_ta_touch := TouchArea {
                width: 130px;
                height: 50px;
                x: 172px;
                Switch {
                    width: parent.width;
                    height: parent.height;
                    text: "TA Helper";
                    toggled => {root.trick_helper_ta = self.checked}
                }
            }
        }
    }

    ToolTip {
        x: skipmaskhint_touch.x + 100px;
        y: skipmaskhint_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 8rem;
        width: 25rem;
        text: "OFF: The adventure mode mask hint cutscenes will play as usual.\n\n"
        + "ON: Sets all adventure mode mask hint cutscenes as 'already seen', "
        + "effectively skipping them.";
        user_is_hovering: skipmaskhint_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: skippodium_touch.x + 100px;
        y: skippodium_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "OFF: The podium cutscenes will play as usual.\n\n"
        + "ON: Automatically inputs the Start-button at the start of each "
        + "podium cutscene, effectively skipping it.";
        user_is_hovering: skippodium_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: skipmaskcongrats_touch.x + 100px;
        y: skipmaskcongrats_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 9rem;
        width: 25rem;
        text: "OFF: The adventure mode voice clips of masks congratulating you for your race prize play as usual.\n\n"
        + "ON: The voice clips of masks will be muted, making it behave as if "
        + "the PAL-exclusive language glitch was active.";
        user_is_hovering: skipmaskcongrats_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: helper_tiziano_touch.x + (parent.width/2) + 20px;
        y: helper_tiziano_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "ON: Modifies the item boxes while performing the 'Tiziano' shortcut.\n"
        + "During regular races on Papu's Pyramid, if the player is in 7th or 8th place, "
        + "every item box is a guaranteed mask item.";
        user_is_hovering: helper_tiziano_touch.has-hover; // <-- references one or more TouchArea below
    }
    ToolTip {
        x: helper_ta_touch.x + (parent.width/2) + 20px;
        y: helper_ta_touch.y + 50px; // <-- references any or no component, not necessarily a TouchArea
        height: 7rem;
        width: 25rem;
        text: "ON: Modifies the item boxes while performing the 'TA' super-shortcut.\n"
        + "During regular races on Tiny Arena, if the player is in 1st place, "
        + "every item box is a guaranteed TNT/Nitro item.";
        user_is_hovering: helper_ta_touch.has-hover; // <-- references one or more TouchArea below
    }
}

component AboutSubmenu inherits Rectangle {
    callback sources_generator();
    callback sources_mod();

    Text {
        y: 10px;
        text: "The CTR Randomizer mod is made by";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    Text {
        y: 30px;
        text: "wiz_taor";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    Text {
        y: 50px;
        text: "Icebound777";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }

    Text {
        y: 100px;
        text: "Sources of this seed generator:";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    TouchArea {
        height: 30px;
        width: 75px;
        y: 120px;
        clicked => {root.sources_generator();}
        Button {
            enabled: false;
            height: 34px;
            width: 80px;
        }
        Image {
            source: @image-url("../res/GitHub_Logo.png");
            height: 30px;
            width: 75px;
        }
    }

    Text {
        y: 160px;
        text: "Sources of the randomizer mod:";
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 800;
        font-size: 10pt;
    }
    TouchArea {
        height: 30px;
        width: 75px;
        y: 180px;
        clicked => {root.sources_mod();}
        Button {
            enabled: false;
            height: 34px;
            width: 80px;
        }
        Image {
            source: @image-url("../res/GitHub_Logo.png");
            height: 30px;
            width: 75px;
        }
    }

    AboutSlint {
        x: 370px;
        y: 170px;
        height: 150px;
    }
    Text {
        y: 300px;
        text: "('User Interface design is my passion' lmao)";
        horizontal-alignment: center;
        vertical-alignment: top;
        font-weight: 800;
        font-size: 8pt;
    }
}

component SettingsMenu inherits TabWidget {
    callback sources_generator();
    callback sources_mod();

    out property <int> shuffle_adventure <=> randomization.shuffle_adventure;
    out property <bool> shuffle_race_rewards <=> randomization.shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys <=> randomization.shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems <=> randomization.shuffle_race_rewards_gems;
    out property <bool> shuffle_race_rewards_plat_relics <=> randomization.shuffle_race_rewards_plat_relics;
    out property <bool> shuffle_warppads <=> randomization.shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas <=> randomization.shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups <=> randomization.shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> randomization.warppad_unlock_requirements;
    out property <bool> autounlock_ctrchallenge_relicrace <=> randomization.autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> randomization.bossgarage_unlock_requirements;

    out property <int> rr_required_minimum_time <=> generalmenu.rr_required_minimum_time;
    out property <bool> rr_require_perfects <=> generalmenu.rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> generalmenu.rr_required_minimum_time;

    out property <bool> qol_skip_mask_hints <=> qolmenu.qol_skip_mask_hints;
    out property <bool> qol_skip_podium <=> qolmenu.qol_skip_podium;
    out property <bool> qol_skip_mask_congrats <=> qolmenu.qol_skip_mask_congrats;
    out property <bool> trick_helper_tiziano <=> qolmenu.trick_helper_tiziano;
    out property <bool> trick_helper_ta <=> qolmenu.trick_helper_ta;

    current-index: 0;
    Tab {
        title: "Randomization";
        randomization := RandomizationSubmenu {}
    }
    Tab {
        title: "General";
        generalmenu := GeneralSubmenu {}
    }
    Tab {
        title: "Quality of Life & Tricks";
        qolmenu := QoLSubmenu {}
    }
    Tab {
        title: "About";
        AboutSubmenu {
            sources_generator() => { root.sources_generator(); }
            sources_mod() => { root.sources_mod(); }
        }
    }
}

component RomOutputBar inherits Rectangle {
    callback gen_seed();
    callback pick_rom();
    in-out property <string> rom_path;
    in property <bool> can_generate;
    in property <int> rom_valid_state;

    out property <bool> write_spoilerlog: true;

    HorizontalLayout {
        Rectangle {
            width: parent.width / 2;
            border-color: black;
            border-width: 1px;

            Text {
                x: 16px;
                text: "ROM:";
                font-weight: 800;
                vertical-alignment: center;
            }
            TouchArea {
                x: 60px;
                width: 350px;
                height: parent.height / 2;
                clicked => {root.pick_rom()}
                LineEdit {
                    width: 350px;
                    placeholder-text: rom_path.is-empty ? "Click here to choose CTR NTSC-U ROM ..." : rom_path;
                    enabled: false;
                }
            }
            Text {
                visible: root.rom_valid_state == 2 || root.rom_valid_state == 3;
                x: 430px;
                text: root.rom_valid_state == 3 ? "Valid": "Invalid";
                font-weight: 800;
                color: root.rom_valid_state == 3 ? green : red;
                vertical-alignment: center;
            }
            Text {
                visible: rom_valid_state == 1;
                x: 430px;
                text: "Validating ROM ...";
                font-weight: 800;
                color: red;
                vertical-alignment: center;
            }
        }
        Rectangle {
            border-color: black;
            border-width: 1px;

                Switch {
                    x: 30px;
                    text: "Generate Spoilerlog";
                    checked: true;
                    toggled => { root.write_spoilerlog = self.checked }
                }

                Button {
                    x: 250px;
                    width: 200px;
                    text: "Generate Seed";
                    height: parent.height * (2/3);
                    enabled: can_generate;
                    clicked => {root.gen_seed()}
                }

                Spinner {
                    x: 460px;
                    progress: 0.9;
                }
        }
    }
}

export component MainWindow inherits Window {
    title: "CTR Randomizer";
    width: 1000px;
    height: 600px;
    callback gen_seed();
    callback pick_rom();
    callback sources_generator();
    callback sources_mod();
    in-out property <string> rom_path;
    in property <bool> can_generate: false;
    in property <int> rom_valid_state: 0;

    out property <bool> write_spoilerlog <=> romoutput.write_spoilerlog;

    out property <int> shuffle_adventure <=> settings.shuffle_adventure;
    out property <bool> shuffle_race_rewards <=> settings.shuffle_race_rewards;
    out property <bool> shuffle_race_rewards_keys <=> settings.shuffle_race_rewards_keys;
    out property <bool> shuffle_race_rewards_gems <=> settings.shuffle_race_rewards_gems;
    out property <bool> shuffle_race_rewards_plat_relics <=> settings.shuffle_race_rewards_plat_relics;
    out property <bool> shuffle_warppads <=> settings.shuffle_warppads;
    out property <bool> shuffle_warppads_battlearenas <=> settings.shuffle_warppads_battlearenas;
    out property <bool> shuffle_warppads_gemcups <=> settings.shuffle_warppads_gemcups;
    out property <int> warppad_unlock_requirements <=> settings.warppad_unlock_requirements;
    out property <bool> autounlock_ctrchallenge_relicrace <=> settings.autounlock_ctrchallenge_relicrace;
    out property <int> bossgarage_unlock_requirements <=> settings.bossgarage_unlock_requirements;

    out property <int> rr_required_minimum_time <=> settings.rr_required_minimum_time;
    out property <bool> rr_require_perfects <=> settings.rr_require_perfects;
    out property <int> oxide_final_challenge_unlock <=> settings.rr_required_minimum_time;

    out property <bool> qol_skip_mask_hints <=> settings.qol_skip_mask_hints;
    out property <bool> qol_skip_podium <=> settings.qol_skip_podium;
    out property <bool> qol_skip_mask_congrats <=> settings.qol_skip_mask_congrats;
    out property <bool> trick_helper_tiziano <=> settings.trick_helper_tiziano;
    out property <bool> trick_helper_ta <=> settings.trick_helper_ta;

    VerticalLayout {
        TitleBar {
            height: parent.height * 0.18;
        }
        //SettingsMetaBar {
        //    height: parent.height * 0.1;
        //}
        settings := SettingsMenu {
            sources_generator() => { root.sources_generator(); }
            sources_mod() => { root.sources_mod(); }
        }
        romoutput := RomOutputBar {
            height: parent.height * 0.13;
            rom_path: root.rom_path;
            can_generate: root.can_generate;
            rom_valid_state: root.rom_valid_state;

            gen_seed() => { root.gen_seed(); }
            pick_rom() => { root.pick_rom(); }
        }
    }
}
